name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
        
    - name: Run linter
      run: yarn lint
      
    - name: Build extension
      run: yarn compile:prod
      
    - name: Package extension
      run: yarn package
      
    - name: Get package version
      id: package-version
      run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
    - name: Upload release asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./partial-diff-${{ steps.package-version.outputs.version }}.vsix
        asset_name: partial-diff-${{ github.event.release.tag_name }}.vsix
        asset_content_type: application/zip
        
    # - name: Publish to VS Code Marketplace
    #   if: github.event_name == 'release' && secrets.VSCE_PAT != ''
    #   run: |
    #     npx @vscode/vsce publish --yarn --packagePath ./partial-diff-*.vsix
    #   env:
    #     VSCE_PAT: ${{ secrets.VSCE_PAT }}
        
    # - name: Publish to Open VSX
    #   if: github.event_name == 'release' && secrets.OVSX_PAT != ''
    #   run: |
    #     npx ovsx publish ./partial-diff-*.vsix
    #   env:
    #     OVSX_PAT: ${{ secrets.OVSX_PAT }}
